services:
  action:
    image: public.ecr.aws/infrastructure-blocks/semver-increment-action:latest
    build:
      context: ../
      dockerfile: docker/action/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:?must be provided}
    container_name: semver-increment-action
