name: Build

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: infrastructure-blocks/typescript-build-workflow/.github/workflows/workflow.yml@v1
    with:
      node-version-file: .nvmrc
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
