name: Git Tag Release From Semver Label

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Build Image
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  git-tag-semver-from-label:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: infrastructure-blocks/git-tag-semver-from-label-workflow/.github/workflows/git-tag-semver-from-label.yml@v2
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.PAT }}
